### ISSUE TITLE
⭐ Proposal Remove stars

### ISSUE THREAD

**Issue by apertureless** [brillout/awesome-vue#19]
As the list is in a cleanup / review state, I would like to propose, to remove the stars / stargazers.

1. [Most](https://github.com/enaqx/awesome-react) [other](https://github.com/sindresorhus/awesome-npm) [awesome](https://github.com/vinta/awesome-python) [list](https://github.com/sindresorhus/awesome) also does not have stargazers 
2. IMO there are more downsides 
3. Includes a rating which does not represent the quality of the package
4. Gets outdated quickly

I think someone started including stargazers to the list and the rest just kept doing it too. (Me included) However imo there are more downsides to this.

Most people will submit their packages pretty early with a low stargazers count. After some time they may have way more stargazers but the list does not update.

Which leads to the second point, that stargazers mostly introduce a rating of the package. More stargazers = more people liking the package = better package. However this is not true. So packages which are older and submitted with more stargazers, will mostly get more attention.

By removing the stars, we make all packages equal.

/discuss ☕

**Comment by brillout** [comment]
Agree and actually there are no stars anymore in the `Components & Libraries` section.

Just in `Resources` there are some star counters left. Wanna remove them and make a PR? Would be awesome.

**Comment by apertureless** [comment]
💪  sure!
