### ISSUE TITLE
[Vue-multiple-pages] Readme is updated

### ISSUE THREAD

**Issue by Plortinus** [brillout/awesome-vue#22]
I updated the readme of [my project](https://github.com/Plortinus/vue-multiple-pages): added the required Vue verion and removed the Chinese description.

**Comment by brillout** [comment]
Thanks for opening the issue & addressing the non-English issue.
I think it would good to elaborate on what exactly this starter is about. E.g. how are you achieving `Mutiple Pages`?

**Comment by Plortinus** [comment]
Thanks for the advice,I added a simple description of [how it works](https://github.com/Plortinus/vue-multiple-pages#how-the-multiple-page-works-assumed-that-you-have-the-basic-knowlege-of-webpack)

**Comment by brillout** [comment]
Ok I understand now, make a PR:)
