### ISSUE TITLE
cleaned http-vue-loader

### ISSUE THREAD

**Issue by FranckFreiburger** [brillout/awesome-vue#7]
http-vue-loader is marked as "readme doesn't say how it works" but http-vue-loader has an "How it works" section : https://github.com/FranckFreiburger/http-vue-loader#how-it-works

**Comment by brillout** [comment]
Yes and I've read it but I'm still confused of how you actually parse changed .vue files? `No node.js environment, no build step.` suggests that you parse them on the client? I mean the purpose of your lib is to test changes so it needs to dynamically build.

**Comment by brillout** [comment]
(I've giving this more thought but I still don't get it.)

**Comment by FranckFreiburger** [comment]
Yes, parsing is done on the client side using
"document.implementation.createHTMLDocument / innerHTML" the vue file is
parsed each time the page is reloaded



*Franck Freiburger*
Développeur IT Full‑Stack Freelance
www.franck-freiburger.com
21 rue de Geroldseck - 67200 Strasbourg
+33 (0)6 75 31 70 91



2017-03-13 23:49 GMT+01:00 Romuald Brillout <notifications@github.com>:

**Comment by brillout** [comment]
How do you compile the template to JS?

**Comment by FranckFreiburger** [comment]
No need to compile the template, I just use the vue's "async components"
feature, then the template is compiled by vue.



*Franck Freiburger*
Développeur IT Full‑Stack Freelance
www.franck-freiburger.com
21 rue de Geroldseck - 67200 Strasbourg
+33 (0)6 75 31 70 91



2017-03-14 0:05 GMT+01:00 Romuald Brillout <notifications@github.com>:

**Comment by brillout** [comment]
Ok so the Vue.js client script does the compiling. It'd be nice to explicitly mention that.

**Comment by FranckFreiburger** [comment]
done, in my "How it works" section.



*Franck Freiburger*
Développeur IT Full‑Stack Freelance
www.franck-freiburger.com
21 rue de Geroldseck - 67200 Strasbourg
+33 (0)6 75 31 70 91



2017-03-14 0:35 GMT+01:00 Romuald Brillout <notifications@github.com>:

**Comment by brillout** [comment]
make a PR and I'll merge it
